### ISSUE TITLE
Add Support for Kotlin Thanks

### ISSUE THREAD

**Issue by 3bdoelnaggar** [joelittlejohn/jsonschema2pojo#1038]

**Comment by ddcruver** [comment]
First I think you need to give more description on your use case because as far as I know these jsonschema2pojo creates objects that are compatible with Kotlin.

**If you just want to generate POJOs:**
One of the things addressed by Kotlin is to reduce the need to produce/generate boiler plate code.  It can create objects without you requiring to write setters/getters/equals method etc.

A quick google search I found this article describing it much better then I could: [`Intro to Data Classes in Kotlin`](https://medium.com/@DarrenAtherton/intro-to-data-classes-in-kotlin-7f956d54365c)

**Providing a schema for you data model:**
Since you are using Kotlin that generates most of the boiler plate code you may want to look into a library that generates a schema based on your objects. See https://github.com/FasterXML/jackson-module-jsonSchema

**Effort to Implement:**
This maybe alot more then you think. These libraries are based on com.sun.codemodel:codemodel which allows you to build classes in an object oriented manner which it does not have for Kotlin.  While Kotlin classes would be much easier to make much of the code resolves around the codemodel library.  Additionally work would need to be made to learn how to annotate the Kotlin self-generated methods or possibly https://github.com/FasterXML/jackson-module-kotlin alleviates this.

**Comment by joelittlejohn** [comment]
See #593 :+1:
