### ISSUE TITLE
Enum with anyOf

### ISSUE THREAD

**Issue by dyutiman** [joelittlejohn/jsonschema2pojo#1050]
Hi,

I am not sure if this is actually an issue or it is working as expected. I am using a 3rd party json schema, so has no control over it.

One property in the schema is defined as:
"IndicatorLED": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/IndicatorLED"
                        },
                        {
                            "type": "null"
                        }
                    ],
                    "description": "The state of the indicator LED, which identifies the system.",
                    "longDescription": "This property shall contain the state of the indicator light, which identifies this system.",
                    "readonly": false
                }

In the definations section the  'IndicatorLED' is an Enum and defined as:
"IndicatorLED": {
            "enum": [
                "Unknown",
                "Lit",
                "Blinking",
                "Off"
            ],
            "enumDeprecated": {
                "Unknown": "This value has been deprecated in favor of returning null if the state is unknown."
            },
            "enumDescriptions": {
                "Blinking": "The indicator LED is blinking.",
                "Lit": "The indicator LED is lit.",
                "Off": "The indicator LED is off.",
                "Unknown": "The state of the indicator LED cannot be determined."
            },
            "enumLongDescriptions": {
                "Blinking": "This value shall represent that the indicator LED is in a blinking state where the LED is being turned on and off in repetition.  If the service does not support this value, it shall reject PATCH or PUT requests containing this value by returning the HTTP 400 (Bad Request) status code.",
                "Lit": "This value shall represent that the indicator LED is in a solid on state.  If the service does not support this value, it shall reject PATCH or PUT requests containing this value by returning the HTTP 400 (Bad Request) status code.",
                "Off": "This value shall represent that the indicator LED is in a solid off state.  If the service does not support this value, it shall reject PATCH or PUT requests containing this value by returning the HTTP 400 (Bad Request) status code.",
                "Unknown": "This value shall represent that the indicator LED is in an unknown state.  The Service shall reject PATCH or PUT requests containing this value by returning the HTTP 400 (Bad Request) status code."
            },
            "enumVersionDeprecated": {
                "Unknown": "v1_1_0"
            },
            "type": "string"
        },

Now, when my java class is build the 'IndicatorLED' property is defined as 'Object' instead of an Enum. Is there anyway I can say that this will be Enum (IndicatorLED) instead of an Object?

Any suggessions will be appriciated.

- thanks

**Comment by dewthefifth** [comment]
I can't find any references to "anyOf" in the code base, and I suspect that it's not supported. More than likely, your type is "Object" because the schema provided does not list a type for the property IndicatorLED.

That said, if anyOf were supported, the problem would be that the property would need to select a type or interface that is compatible with all possible types inside of the anyOf. The easiest way to do this would be to select the type of Object, but it may be possible to somehow figure out a "better fit". In your specific case, the better fit is the IndicatorLED enum type, since the only other entry in "anyOf" is null. This could potentially be a corner case we could identify.

I've marked the ticket as an enhancement for now, as I think it's possible we could do something to mitigate the issue. However, it will likely need to be discussed further.

**Comment by joelittlejohn** [comment]
Yeah, no support for anyOf in this plugin and this is discussed widely elsewhere.

**Comment by dyutiman** [comment]
Hi Joe,

It would be nice if you can please provide some links where the discussions are going on for anyOf. It will be helpful as references.

- thanks
