### ISSUE TITLE
builder class name

### ISSUE THREAD

**Issue by ogerardin** [joelittlejohn/jsonschema2pojo#1090]
When generating with `useInnerClassBuilders=true`, the builder inner classes are named like the enclosing class + "Builder". 
Why is the builder class not just named `Builder`? It is already in the namespace of its enclosing class, so there is no need to repeat its name. 

In the current situation, unless you explicitly import the inner class, you have to refer to it as `MyClass.MyClassBuilder`. I'd rather write `MyClass.Builder` 

Also, generating a static method on the enclosing class to get a builder instance would be nice, and possibly make the previous point irrelevant:
```
  public static MyClass.Builder builder() {
    return new MyClass.Builder();
  }
```

**Comment by joelittlejohn** [comment]
Yes, I think you're right. For minor breaking changes like this (easily accommodated with a simple edit) we typically increment the minor version number, so we could move to 1.1.x for this change.

**Comment by dewthefifth** [comment]
This is intentional, because it's not uncommon to use two different classes and have multiple builders imported. 

If it's named Builder than one of those classes must be fully qualified.
Builder (for the imported A.Builder)
B.Builder (for the imported B)
foo.bar.C.Builder (for the unimported C)

If you import the builder itself (which you totally should, you're using the class)
ABuilder (for the imported A.ABuilder)
BBuilder (for the imported B.Builder)
foo.bar.C.CBuilder (for the unimported CBuilder)

Effectively this boils down to a matter of preference, and for the people using the capability I wouldn't call it a minor breaking change since it will literally change every single usage of their builders.

I recommend adding a "BuilderNameFactory", which defaults to the naming I originally implemented but can be configured to any class you want so people can choose to name their builders to their hearts content.

**Comment by ogerardin** [comment]
> This is intentional, because it's not uncommon to use two different classes and have multiple builders imported.

Correct, so with my proposal instead of importing the builders and writing ABuilder, BBuilder etc., you can just omit the imports and refer to A.Builder, B.Builder etc. 

> I recommend adding a "BuilderNameFactory", which defaults to the naming I originally implemented but can be configured to any class you want so people can choose to name their builders to their hearts content.

That would be the best thing, so it wouldn't even have to be a breaking change.

**Comment by joelittlejohn** [comment]
This is a minor annoyance and not something we should introduce yet another configurable option for. We can't stretch to everyone's possible style of Java, this plugin just has to choose a style.

I'm closing this one as I think the decision has basically been made already, and although there might be competing opinions about what's the nicest style, it's done.
