### ISSUE TITLE
Include meta information in generated class?

### ISSUE THREAD

**Issue by ogerardin** [joelittlejohn/jsonschema2pojo#1097]
It would be nice to include some metadada in the generated classes.
I'm thinking :
- source schema file
- generation date and time
- version of jsonschema2pojo

What do you think?

**Comment by joelittlejohn** [comment]
We had problems in the past with the `@Generated` annotation because it wasn't available by default in Android (and this confused people). I'd also be worried that including generation date and time, and version of jsonschema2pojo, would cause a lot of change in these files when there is no change needed. Adding the source schema file is a harder problem than you might think (and subject to some edge-cases or confusing results when refs of different kinds are used).

I think this is a nice idea but maybe adding 'jsonschema2pojo' into the javadoc is the only practical metadata we can add.

**Comment by ogerardin** [comment]
I was thinking comments rather than annotation. And of course it should be an option.
Creating changes is not a problem imho as these files should not be checked into the VCS.
Actually the source file would be the most useful feature to me, I've found myself often looking at a generated class and wondering where it came from, which is not obvious.

**Comment by joelittlejohn** [comment]
We include the generated annotation again now with a reference to jsonschema2pojo. I have no desire to make all these types different every time the generator runs or generate configurable metadata. Thanks for the suggestion though.
