### ISSUE TITLE
Feature: Can Lombok annotations can be addded as an option ?

### ISSUE THREAD

**Issue by vinishgeorge** [joelittlejohn/jsonschema2pojo#1113]
Can Lombok annotations can be addded as an option ?

**Comment by eirnym** [comment]
Which annotations do you want to add? 

BTW: For XJC I saw no good plugins with lombok annotations, so I don't expect any good implementation here.

**Comment by vinishgeorge** [comment]
based on users selection of the following options 

Include getters and setters
Include constructors
Include hashCode and equals
Include toString

the Lombok annotations can be added.

**Comment by eirnym** [comment]
and then add all other code generators on users' pleasure. 

I'd prefer to add a possibility for a plugin which will provide these modifications rather than add this into this generator itself.

The reasons are quite simple:
* this generator uses java 8 and able to produce java6-compatible code, which could be crucial. With a plugin you can easily manage versions and available features
* not everybody uses or wants to use lombok, as there're other generators and some users want to use no such dependency at all. Current generated sources don't depend on any other libraries (except for dates and json generator annotations)

**Comment by joelittlejohn** [comment]
@vinishgeorge This is already open as #166. If you have thoughts on what you'd want and need, please add them there.
