### ISSUE TITLE
Android Parcelable unused import

### ISSUE THREAD

**Issue by hannesa2** [joelittlejohn/jsonschema2pojo#1150]
![image](https://user-images.githubusercontent.com/3314607/90005200-23fa4c80-dc97-11ea-9fd0-5d95af19ab21.png)

How to get rid of this unused imports ?

**Comment by hannesa2** [comment]
This is the only place I found, but to be honest, I don't understand what's going on there

https://github.com/joelittlejohn/jsonschema2pojo/blob/98d1e6ab69ba7d9cda851d1dc901e6d2a54062e6/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/ParcelableHelper.java#L52

**Comment by unkish** [comment]
To get rid of the imports code would have to be modified.

As `android.os.Parcelable.Creator` is a nested interface defined within `android.os.Parcelable` and latter is imported due to:
https://github.com/joelittlejohn/jsonschema2pojo/blob/98d1e6ab69ba7d9cda851d1dc901e6d2a54062e6/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java#L157

Changing
https://github.com/joelittlejohn/jsonschema2pojo/blob/98d1e6ab69ba7d9cda851d1dc901e6d2a54062e6/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/ParcelableHelper.java#L52
to:
`JClass creatorType = jclass.owner().directClass("Creator").narrow(jclass);`
would yield desired result.

Note however that since `ParcelableHelper::addCreator` is `public` such a change could cause issues in case method would be invoked without call that would generate import of `android.os.Parcelable`

**Comment by eirnym** [comment]
I don't see any reason against importing the `android.os.Parcelable.Creator` class, but I see no reason to have it twice in imports.

**Comment by hannesa2** [comment]
If you use `ktLint`, you will run into errors wtih unused imports.
It's simply noise
