### ISSUE TITLE
@Generated annotation is not added to the generated classes

### ISSUE THREAD

**Issue by sergeykad** [joelittlejohn/jsonschema2pojo#1162]
The [@Generated](https://docs.oracle.com/javase/10/docs/api/javax/annotation/processing/Generated.html) annotation is handy to quickly spot generated classes.
In addition, some tools like [Google Error Prone](https://github.com/google/error-prone), rely on it to distinguish between the regular and generated code. The missing annotation makes Error Prone practically unusable since hundreds of errors are reported for the code generated by jsonschema2pojo.

**Comment by joelittlejohn** [comment]
You might be interested in this solution: https://github.com/joelittlejohn/jsonschema2pojo/issues/835#issuecomment-385551880. You can remove the paths that contain generated output from Error Prone's scanning.

We originally removed @Generated because it caused hassle for Android users:

https://github.com/joelittlejohn/jsonschema2pojo/issues/577

Their classes would not compile without adding an additional library and it caused a lot of questions.

I do agree though, it's a lot nicer to annotate these generated classes correctly because a lot of tools will read that annotation.

We still support Java 8 though so I think we need to add `javax.annotation.Generated` or `javax.annotation.processing.Generated` depending on what we find is available.

**Comment by sergeykad** [comment]
Thanks for the detailed explanation. Looks like I inadvertently duplicated an issue. I am closing this one and will add comments to the #835
