### ISSUE TITLE
Multiple dateTime types in one schema

### ISSUE THREAD

**Issue by himslm01** [joelittlejohn/jsonschema2pojo#1163]
We have a JSON schema where most of the `string` `date-time` properties should be converted into `java.time.OffsetDateTime`  objects:

```
        "creationDate": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp showing when the mediaitem was created."
        },

```
but one in particular needs to be converted into a `java.time.LocalDateTime`
```
        "eventDate": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp the user sets for displaying when an event happened. Due to the defined Java dateTimeType it is stored as UTC but to be treated as if no timezone."
        },
```
We have defined the default dateTimeType:
```
  dateTimeType = "java.time.OffsetDateTime"
```
We would like to be able to change the type for this one property, but we have not found a way to do that. Therefore we have to add notes to our JSON schema and comments in our code to ignore the timezone in the `OffsetDateTime` object - which is ugly and prone to errors and being forgotten in the years to come.

Are we missing something, or is this an enhancement that could be included in a future release?

**Comment by joelittlejohn** [comment]
I think one way to solve this would be to add `"existingJavaType": "java.time.LocalDateTime"` to the schema for eventDate.

**Comment by jonathansloman** [comment]
> existingJavaType

Hi, we tried that (I'm a colleague of himslm01) and unmarshalling worked okay, but marshalling didn't, ended up with something like:
"eventDate":[2015,7,10,8,51,25,648000000]
at a guess due to jackson treating it as a java object rather than a date with a format string. We could write custom serialisers everywhere, but that starts getting a bit nasty. You already have the customDateFormat option to override the date format at the per-field level, so it would seem to make sense to allow a customDateTimeType to override dateTimeType at the per-field level?

**Comment by joelittlejohn** [comment]
> customDateFormat option to override the date format at the per-field level, so it would seem to make sense to allow a customDateTimeType to override dateTimeType at the per-field level?

Even if we allow `customDateTimeType` to override `dateTimeType` at a field level, this won't solve the problem of marshalling causing that bad output. You shouldn't need to write custom serializers everywhere though, just use https://github.com/FasterXML/jackson-modules-java8.

**Comment by jonathansloman** [comment]
It may be because I thought that to use existingJavaType, you had to have type="object" rather than type="string".

That may have been my misunderstanding. I've tried this now:

`       "eventDate": {
            "type": "string",
            "format": "date-time",
            "existingJavaType": "java.time.LocalDateTime"
        }
`

which results in

`    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSX", timezone = "UTC")
    @JsonProperty("eventDate")
    @JsonPropertyDescription("Timestamp showing when an event happened. This could be a transmission event or a recording event. Stored as UTC but to be treated as if no timezone.")
    @NotNull
    private LocalDateTime eventDate;
`

but when serialising get: Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds

So maybe need to do something with a custom date format. Anyway yes, looks like existingJavaType will work, just my misunderstanding that it only applied to object fields.
