### ISSUE TITLE
HTTPS 4 jsonschema2pojo

### ISSUE THREAD

**Issue by dbendlin** [joelittlejohn/jsonschema2pojo#1168]
Did you consider using Letsencript to enable <http://www.jsonschema2pojo.org/> to use HTTPS?

Not sure how to help considering Letsencrypt configuration is usually done outside the source code =/

**Comment by dbendlin** [comment]
Please check this [results](https://www.immuniweb.com/ssl/?id=HXqpIeGm)

**Comment by joelittlejohn** [comment]
We use free a Heroko dyno, and I think they don't offer Let's Encrypt integration on custom domains for free dynos - you need to be paying for at least Hobby dynos to get TLS. So one option is to upgrade to a Hobby dyno, which should cost ~$84/year.

In the meantime though, it's possible to use https://jsonschema2pojo.herokuapp.com. That site is currently broken because we have not used protocol-relative URLs to refer to css and javascript resources, but I think we could easily change that and have the site function correctly.

**Comment by joelittlejohn** [comment]
I've fixed those protocol-relative URLs so that link works now.
