### ISSUE TITLE
Array with minItems:1, should not be defaulted to empty List

### ISSUE THREAD

**Issue by ludekz** [joelittlejohn/jsonschema2pojo#1191]
In json we have

```
"STATE_RESIDENCES": {
  "type": "array",
  "minItems": 1,
  "maxItems": 100,
  "additionalItems": false,
  "items": {
    "$ref": "#/definitions/STATE_RESIDENCE"
  }
```
meaning that element STATE_RESIDENCES should not be there at all, or there should be at least one item in array.
This is generated as empty list 
```
@JsonProperty("STATE_RESIDENCES")
@Size(min = 1, max = 100)
@Valid
private List<StateResidence> stateResidences = new ArrayList<StateResidence>();
```
and in request it is filled as 
`"STATE_RESIDENCES": []`

and it is not valid, because there is not at least one item. 
In default when array cannot be empty, generate should not create empty list. Maybe just handle it nicely in getter and setter, but let serialization to json not fill it.

**Comment by joelittlejohn** [comment]
You can disable this defaulting of arrays.

We don't really ever try to ensure that instances are always valid (cannot be in an invalid state). We only try to make sure that we can represent valid instances. Some people like to default arrays with an empty list for convenience, so that there's one there when they are building a value. There are endless ways in which an instance, when created, might not validate according to the schema. You must make sure you make the instance valid before it must validate.
