### ISSUE TITLE
Inner class builder inheritance

### ISSUE THREAD

**Issue by marcodallasanta** [joelittlejohn/jsonschema2pojo#1196]
Hi, you should consider the possibility to make the inner class builder implement an interface. In my specific case I need the builder to implement an interface with generics. This could be defined in configurations. 
My proposal is to add two properties:

```
builderImplements: `fully.qualified.java.type` // could be also a generic type ex. `fully.qualified.java.type<T>`
builderExtends: `fully.qualified.java.type` // same as above
```

Obviously when one of these has a value, the builder generated will implement or extend the type specified.

**Comment by joelittlejohn** [comment]
Hi. Thanks for the suggestion.

Sorry, but it's not the goal of this plugin to produce any possible desired Java output. The problem is that every time we add features like this, they require support and maintenance forever. Everyone has some change they would like to make to Java output because they have some idea about extending the code to fit some other requirements in their system. We simply can't meet all these demands.

Of course, you're free to fork and extend this project to your own needs.
