### ISSUE TITLE
ClassAlreadyExistsException for Enum creation

### ISSUE THREAD

**Issue by ostfale** [joelittlejohn/jsonschema2pojo#1243]
Just processed current version of OCPP 2.0.1. json schema files. It generates the correct output but shows a lot of error messages. 

`[INFO] --- jsonschema2pojo-maven-plugin:1.1.1:generate (default) @ ocpp-v2x ---
[ERROR] Could not create enum.
org.jsonschema2pojo.exception.ClassAlreadyExistsException
    at org.jsonschema2pojo.rules.EnumRule.createEnum (EnumRule.java:366)
    at org.jsonschema2pojo.rules.EnumRule.apply (EnumRule.java:116)
    at org.jsonschema2pojo.rules.EnumRule.apply (EnumRule.java:68)
    at org.jsonschema2pojo.rules.SchemaRule.apply (SchemaRule.java:83)
    at org.jsonschema2pojo.rules.SchemaRule.apply (SchemaRule.java:76)
    at org.jsonschema2pojo.rules.SchemaRule.apply (SchemaRule.java:38)
    at org.jsonschema2pojo.rules.PropertyRule.apply (PropertyRule.java:71)
    at org.jsonschema2pojo.rules.PropertyRule.apply (PropertyRule.java:41)
    at org.jsonschema2pojo.rules.PropertiesRule.apply (PropertiesRule.java:70)
    at org.jsonschema2pojo.rules.PropertiesRule.apply (PropertiesRule.java:38)
    at org.jsonschema2pojo.rules.ObjectRule.apply (ObjectRule.java:121)
    at org.jsonschema2pojo.rules.ObjectRule.apply (ObjectRule.java:66)
    at org.jsonschema2pojo.rules.TypeRule.apply (TypeRule.java:83)
    at org.jsonschema2pojo.rules.TypeRule.apply (TypeRule.java:38)
    at org.jsonschema2pojo.rules.SchemaRule.apply (SchemaRule.java:85)
    at org.jsonschema2pojo.rules.SchemaRule.apply (SchemaRule.java:76)
    at org.jsonschema2pojo.rules.SchemaRule.apply (SchemaRule.java:38)
    at org.jsonschema2pojo.rules.PropertyRule.apply (PropertyRule.java:71)
    at org.jsonschema2pojo.rules.PropertyRule.apply (PropertyRule.java:41)
    at org.jsonschema2pojo.rules.PropertiesRule.apply (PropertiesRule.java:70)
    at org.jsonschema2pojo.rules.PropertiesRule.apply (PropertiesRule.java:38)
    at org.jsonschema2pojo.rules.ObjectRule.apply (ObjectRule.java:121)
    at org.jsonschema2pojo.rules.ObjectRule.apply (ObjectRule.java:66)
    at org.jsonschema2pojo.rules.TypeRule.apply (TypeRule.java:83)
`

**Comment by joelittlejohn** [comment]
Hi. Do you have a link to the schema files you used by any chance? Are they available for download somewhere?

**Comment by ostfale** [comment]
You can download from :  https://www.openchargealliance.org/downloads/ . There is a folder with json schema files.

**Comment by joelittlejohn** [comment]
Um, downloading this requires that I provide a name, organisation, email address and phone number. I don't want to do that.

If you can provide the schemas I can investigate.

**Comment by ostfale** [comment]
Ok, here we are :-)

 

Von: Joe Littlejohn ***@***.***> 
Gesendet: Samstag, 24. April 2021 21:46
An: joelittlejohn/jsonschema2pojo ***@***.***>
Cc: Uwe Sauerbrei ***@***.***>; Author ***@***.***>
Betreff: Re: [joelittlejohn/jsonschema2pojo] ClassAlreadyExistsException for Enum creation (#1243)

 

Um, downloading this requires that I provide a name, organisation, email address and phone number. I don't want to do that.

If you can provide the schemas I can investigate.

**Comment by joelittlejohn** [comment]
You can't attach files to a github issue via email I'm afraid, but you can drag and drop them onto the comment box.

**Comment by ostfale** [comment]
[jsonTest.zip](https://github.com/joelittlejohn/jsonschema2pojo/files/6370570/jsonTest.zip)

**Comment by eirnym** [comment]
> Um, downloading this requires that I provide a name, organisation, email address and phone number. I don't want to do that.
> 
You don't need to provide real data

**Comment by joelittlejohn** [comment]
@eirnym the file is emailed too you, so yes you do. Also, I have no interest in filling out a form with fake details.

@ostfale thanks for the zip.

**Comment by eirnym** [comment]
@joelittlejohn I have email dedicated for such sites, so no.

**Comment by joelittlejohn** [comment]
@ostfale The problem here looks to be that these schemas repeat definitions many times, but they also specify `javaType` so jsonschema2pojo is being instructed to use the same class name. For instance, I see that GenericStatusEnumType is repeated in GetCompositeScheduleResponse.json, NotifyEVChargingScheduleResponse.json, PublishFirmwareResponse.json, SetMonitoringLevelResponse.json and SignCertificateResponse.json.

I can think of a couple of options here:

1. Remove javaType across all of these schemas. The enums will become inner classes. Note that you will still get many duplicate classes generated for things like SalesTariff because they are declared in many different places.  
2. Declare types like GenericStatusEnumType *once* and use `$ref` to refer to them in different places.

My guess is that you are not expected to generate types for all of these schemas but instead use each schema in isolation (?). I'm not sure why there is so much repetition in the definition but I'm afraid jsonschema2pojo will only treat schemas as declaring the actual same thing if $ref is used.

**Comment by ostfale** [comment]
@joelittlejohn The files are part of the official specification in communication between a charging point and the management service. All messages are needed for communication.  From my point of view is the thrown exception not an error but a warning?

**Comment by joelittlejohn** [comment]
> The files are part of the official specification in communication between a charging point and the management service. All messages are needed for communication.

Yes, it's a strange one because the way that these schemas are currently written makes me think that whoever wrote them did so with this tool in mind maybe. For instance, they have `javaType`. However for a few different reasons I don't think any version of jsonschema2pojo could support these schemas.

We recently had to apply a workaround for a bug in CodeModel that means that any enum generated into the default package would be defined incorrectly as a class (instead of an enum). We no longer generate types into the default package, even when no package name is given in javaType. It means that previous versions of this tool would not have produced correct output with these schemas. Maybe the person that wrote them was targeting a modified version of this tool? Maybe it's a coincidence that they chose to include 'javaType'.

> From my point of view is the thrown exception not an error but a warning?

This good be a good solution. Strictly speaking I guess if the contents of the schemas cause one type to be written over another because javaType implies this should be done, we could just print an obvious warning.

I'd be interested if you could try using a modified version of this plugin (clone this repo, make changes, `mvn install` or `mvn install -DskipTests` if necessary, then try using the snapshot version) and decide if the output is adequate.

Unfortunately I think you will find that this is not the only issue. I also noticed a large amount of duplication in the schemas where $ref is not used, leading to a lot of new, duplicated types being generated. These are unrelated to the ones that are causing the ClassAlreadyExistsExceptions. I expect this means the output is really not what you want.

**Comment by ostfale** [comment]
The OCPP spec has already some history and I guess, it will not be the last version. After your remarks I think there is no need for further action. If I run the result it is working, the error messages are annoying, but I can live with it. :-) If it is spec fault, no further options in the plugin configuratin make sense. You can close the issue, if you want.

**Comment by joelittlejohn** [comment]
Thanks @ostfale! 👍
