### ISSUE TITLE
StackOverflow with maven plugin

### ISSUE THREAD

**Issue by wardev** [joelittlejohn/jsonschema2pojo#128]
I tried running the maven plugin with this[1] schema. The plugin failed with a stack overflow error. I tried increasing the stack size up to 1G, but it didn't help. The full stack trace and debugging output is available here[2].

[1] https://github.com/AnalyticalGraphicsInc/czml-writer/tree/master/Schema
[2] https://gist.github.com/wardev/6808c90bb63e27cc3f1b

**Comment by chunkiat82** [comment]
@vidia I'm still having this issue. Were you able to solve it?

Tks

**Comment by unkish** [comment]
@joelittlejohn I think this issue could be closed as it was fixed with #560

`https://json-schema.org/draft-04/hyper-schema` was taken as a sample schema.
Running `jsonschema2pojo -s hyper-schema.json -t out` yielded:

- `jsonschema2pojo-0.4.22` failed with `Exception in thread "main" java.lang.StackOverflowError`
- `jsonschema2pojo-0.4.23` succeeded, generating: `HyperSchema.java`,  `Link.java`,  `Media.java`
