### ISSUE TITLE
Error in class name when generating pojo for json where node is an array and nodename ends with an 's'

### ISSUE THREAD

**Issue by adbdkb** [joelittlejohn/jsonschema2pojo#1304]
Here is my json

Sorry, I have formatted the json in the code tags `` - but somehow it is not taking it

```
{
  "id": "1",
  "description": "Generate Schema where last char of nodename is s",
  "DataElements": {
    "Event": {
      "CycleDate": "2006-08-04",
      "Description": "Contribution",
      "GrossAmt": "69839.73",
      "RecEffDate": "2020-05-19",
      "RecStatus": "A",
      "EventBenefits":
      {
        "BenefitID": "BENE0011",
        "Rate": "12.345678",
        "Amount": "100000.01",
        "LastModifyDateTime": "2020-06-15T04:23:56.231",
        "DateReceived": "2020-05-20",
        "RateEffDate": "2020-05-20"
      },
      "EventBills": [
        {
          "BillMailCode": "BillOwnRes",
          "BillAmount": "100.08",
          "BillDate": "2010-01-04"
        }
      ]
    }
  }
}
```

When I use the jsonschema2pojo plugin to generate the classes, the EventBenefits class is created with correct name - 'EventBenefits',  but the EventBills class is created as 'EventBill'.

That seems odd - in my actual json, the name of the node was EventCodeBasis - which created a class with name 'EventCodeBasi'   which is how I realised - hence created above sample

**Comment by unkish** [comment]
Quote from an [answer](https://github.com/joelittlejohn/jsonschema2pojo/issues/1275#issuecomment-866767985) by author of the library:
> Yes, so the issue here is that when we see an array like 'Products' we make this singular for the item class name, like 'Product'

In given case same rule has been applied: since `EventBills` is an array the resulting class name is singularized by [`Inflector`](https://github.com/joelittlejohn/jsonschema2pojo/blob/0de10cfd3396adcc44d00e2bf828ff8596c38b71/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/Inflector.java#L130) to `EventBill`

The very same rule is also applied in case of `EventCodeBasis` turning it into `EventCodeBasi`
By [definition](https://www.thefreedictionary.com/basis) plural form of `basis` is `bases`, thus changing `EventCodeBasis` to `EventCodeBases` would have yielded expected result.

**Comment by joelittlejohn** [comment]
As unkish says, we use the inflector so that, for instance, an array of 'bills' will interpreted such that each item is a 'bill'. In future we may allow more control over this via e.g. #148, but for now if you want full control then you must create a JSON Schema and use rules like `javaType` to influence the class name.
