### ISSUE TITLE
Integers are now Long and Date are now String on https://www.jsonschema2pojo.org/

### ISSUE THREAD

**Issue by vicnevicne** [joelittlejohn/jsonschema2pojo#1308]
Hi,
I used https://www.jsonschema2pojo.org/ one year ago to generate some classes and now have to re-generate them due to some API changes, but I notice some fields in the generated classes have changed type, namely numbers are now Long instead of Integer (I made sure the "Use long integers" was **not** checked), and Date fields are now Strings.
Is it intentional or a bug ?

Note: I generate the files starting from a JSON example (not schema), attached.
[example_ok.zip](https://github.com/joelittlejohn/jsonschema2pojo/files/6988355/example_ok.zip)

Keep on the good work !

(Edit: original attachment was not the right file. Fixed.)

**Comment by joelittlejohn** [comment]
Hi. The reason that the numbers are long relates to #971. We now detect whether long is required by looking at the size of the value. Since 1234567890123 is greater than Integer.MAX_VALUE (which is 2147483647) you will get a Long (because a Java integer cannot hold this value).

Regarding dates, we don't have a way to produce dates when you use a JSON example as input, so I think you must have edited these manually in the past (see #303).

**Comment by vicnevicne** [comment]
Thanks for the quick reply.
Makes sense for long/int, I should have thought of that. Nice improvement !
As for Date fields, I have no memory of changing them, but you must be right for sure. I think that improvement would make sense. Basically, a parse trial and error would do I guess.
Thanks again
