### ISSUE TITLE
Apache Flink Jackson library wrapper

### ISSUE THREAD

**Issue by deweil** [joelittlejohn/jsonschema2pojo#1353]
Hi together,

I have a question / issue about the import of the jackson library.
In Apache Flink they build a wrapper around jackson and so the imports have to be different than the default jackson one. E.g. The following import has to be replaced by:

Default:  
`com.fasterxml.jackson.annotation`

Replaced by:  
`org.apache.flink.shaded.jackson2.com.fasterxml.jackson.annotation`

Is there any way to do that? I couldn't find anything in the documentation about that.

**Comment by joelittlejohn** [comment]
Hi. The way to achieve this is to create an 'annotator' that adds these flink annotations. You can copy the Jackson2Annotator and make some edits. Then you can build it as a separate module, then use the customAnnotator config option for jsonschema2pojo.

If you do this, it would be great to share your code on GitHub so that others can find you annotator.
