### ISSUE TITLE
missing Java code generation for an ordinary string data type

### ISSUE THREAD

**Issue by Markus-Elfring** [joelittlejohn/jsonschema2pojo#1424]
I am trying the current software release out.

```
Markus_Elfring@…:~/Downloads/Freeware/jsonschema2pojo-1.1.2/bin> sh jsonschema2pojo -s ~/Test/JSON/Schemas/GTIN-unchecked-Schema1.json -t ~/Bau/JSON/Schemas/GTIN
```

[Now I wonder again](https://github.com/joelittlejohn/jsonschema2pojo/issues/1419 "Clarification attempt from 2022-08-01") why I do not see that desired Java source files were generated in the specified target directory according to my simple JSON schema example.

```JSON
{
"$schema": "http://json-schema.org/draft/2020-12/schema",
"$id": "https://example.com/schemas/GTIN",
"type": "string"
}
```

:crystal_ball: How should the tool implementation be improved further?

**Comment by joelittlejohn** [comment]
There's nothing to generate for this schema so no Java source files are produced. 

The point of this library is to support a process known as 'data binding'. For this we need Java types that JSON data can be mapped to. You can then use a library like Jackson or gson to 'bind' JSON data to instances of your generated types. A typical way to do this is using the Jackson ObjectMapper.

In your example above, you don't need any types to bind your data to, since the only values you expect to receive are of type 'string'. These values can be represented using java.lang.String, so we do not need to generate any new types.

**Comment by Markus-Elfring** [comment]
:thought_balloon: I find it questionable to exclude code generation for stanndard Java data types.

:eyes: I am still looking for a better parser generator also according to JSON schemas.

**Comment by joelittlejohn** [comment]
Java's type system is quite limited. For instance, we can't create type aliases for this case. I don't believe it makes sense to represent a string using any other type than java.lang.String.

**Comment by Markus-Elfring** [comment]
Do any parser generators for a programming language (like Java) exist so that safer applications can be developed for JSON schemas in more convenient ways?
