### ISSUE TITLE
Recursive $ref failed

### ISSUE THREAD

**Issue by princehaku** [joelittlejohn/jsonschema2pojo#250]
the sample
```json
{
        "type" : "object",
        "properties" : {
          "child1" : {
                "type" : "string"
            },
          "child2" :{
               "$ref" : "#/properties/child1"
            }
        }
}
```
it doesn't work

got error   There's a problem: URI is not absolute

**Comment by KalinKanev** [comment]
I can see that this issue is kind of old but I'm running in the same problem. Is there a plan to fix it ?

**Comment by joelittlejohn** [comment]
So it looks like the original example works correctly (the simple case) - that issue was fixed a long time ago. There is a more complicated example here: https://github.com/joelittlejohn/jsonschema2pojo/issues/250#issuecomment-56911814 and this does not work. This is not a problem with simple recursive refs but a problem with having a schema that is referred to by a fragment ref then using another fragment ref to refer outside the inner schema. This only seems to affect the case where there is no parent file (the schema is supplied as a string), and jsonschema2pojo.org is one such place.
