### ISSUE TITLE
Gradle jsonschema2pojo plugin (0.4.6) is not compatible with the Android plugins

### ISSUE THREAD

**Issue by TheNightbear** [joelittlejohn/jsonschema2pojo#266]
I followed the instructions [here](https://github.com/joelittlejohn/jsonschema2pojo/tree/master/jsonschema2pojo-gradle-plugin) to configure the `Gradle jsonschema2pojo plugin` in Android Studio.
I'm using 
- Gradle jsonschema2pojo plugin version: 0.4.6
- Android Studio: 0.8.14

Gradle runs fine, except the final error message:

*Gradle 'Frameolous' project refresh failed
Error:The 'java' plugin has been applied, but it is not compatible with the Android plugins.*

**Comment by joelittlejohn** [comment]
Thanks for the info Ben. This should someone pick this up.

I'm not a Gradle user so I can't verify this change particularly well. We need a pull request here from someone that uses the Gradle plugin and is able to test this effectively.

**Comment by ben-manes** [comment]
Well, you'd want someone who uses Android to tests this since I haven't worked with it yet. The Java portion is easy to verify, especially if we add a few Spock tests.

**Comment by samskiter** [comment]
Hi, I'm happy to test - is this ready to try out now?

**Comment by samskiter** [comment]
By the way, I've got my generator working by making a new android studio Java module with only the generator inside. The targetDirectory has to look like this:

```
targetDirectory = file("${project.rootDir}/build/generated-sources/js2p")
```

**Comment by ben-manes** [comment]
Hi @samskiter 

The changes aren't in master but are easy to apply. If you prefer I can make the changes in a fork that you can pull, or you can apply the changes I described earlier.

To test locally, you would probably need to build a new SNAPSHOT version, update your gradle dependency version, and add `mavenLocal()` to your repository listings. Then you should be able to run a Gradle build with the local changes to the plugin.

Alternatively if you setup a sample project that demonstrated this bug, I could attempt to make the fixes. I'm sure setting up an Android project is simple, but I just never tried. We could include the android sample under plugin's example folder, which is a stopgap since unfortunately I didn't bother to write tests when I originally wrote the plugin for my personal usage.

**Comment by samskiter** [comment]
https://github.com/samskiter/jsonschema2pojoAndroidExample done :)

**Comment by ben-manes** [comment]
Thanks for the example! Please take a look at the pull request with the proposed fix.
