### ISSUE TITLE
Generate base object for patterns in schema

### ISSUE THREAD

**Issue by Smitty010** [joelittlejohn/jsonschema2pojo#304]
This enhancement would be an option to generate the object for patterns in the schema.  It would be optioned off by default.  If turned on, then a base class is generated for the item.  The programmer would need to add in the actual pattern names in the appropriate pojo for their particular instance.  The object generated would have a TODO mark and a comment field describing the purpose of the object and how to tie it in.

**Comment by joelittlejohn** [comment]
@Smitty010 In the case you're describing here, are you saying that patternProperties is used simply as a shortcut to describe many property names with one definition? It sounds like the class you create by manually implementing 'the actual pattern names' would not be valid for some valid input data.

Using the example you linked to on #301 (http://www.iptc.org/std/ninjs/ninjs-schema_1.1.json), the renditions object may have *any* properties with a name that match `^[a-zA-Z0-9]+`. So what does it mean to manually implement the actual names?

**Comment by joelittlejohn** [comment]
I'm going to close this one as a wontfix, since as I mentioned on #301 I'm concerned that there isn't a significant minority of users that would use this and hence I don't think it's worth the time to implement or maintain in the core of this plugin. This feels like a bit of a special case rather than a more generally applicable solution to patternProperties.
