### ISSUE TITLE
unable to override existing properties when extends is used

### ISSUE THREAD

**Issue by tstack** [joelittlejohn/jsonschema2pojo#336]
I have a schema with an integer property that is being extended to set the default value of the property.  Unfortunately, the generated code does not compile since the child class defines a new method with the same name, but a different return type (Object since the type is not defined in the extended property).

Here's the definition of the property:

        "priority_index" : {
          "description" : "Display priority of this property - used to sort",
          "type"        : "number",
          "required"    : false,
          "readonly"    : true
        },

And, then it's overridden in the extends with:

                "priority_index" : {
                  "default" : 30
                }

Anyhow, there seem to be at least a couple issues with the current approach to extends: a new field in the child class is defined, even though it exists in the parent; the default values for fields should be in the constructor instead of in the field definition, so that it can be overridden; getters/setters should not be generated for overridden fields.

So, one question I have is whether extends should be done through Java class inheritance?  Are people leveraging the class hierarchy that is created?  Would a better way be to just define the class with all of the fields, including those in the definition that is being extended, and not do any Java class inheritance.

**Comment by joelittlejohn** [comment]
Hi Tim. The support for `extends` in this way has existed since the very earliest days of this plugin. It's naive, it satisfies a variety of use-cases but it's in no way an exhaustive attempt to cover all json schema cases and limitations like the one you've described are expected.

Given that `extends` is now deprecated, I think any effort we make would be better spent on support for `allOf`, `anyOf`, `oneOf` from draft04. I'm going to mark this as a wontfix as I don't think this problem is common enough to warrant a completely new, alternative implementation of `extends`.
