### ISSUE TITLE
Links broken in README

### ISSUE THREAD

**Issue by ctrimble** [joelittlejohn/jsonschema2pojo#343]
Documentation links for maven plugin and ant task are broken in project README.  It looks like they point to the correct location, but the 4.11 documentation for these items is not published.

**Comment by joelittlejohn** [comment]
Dammit, every time I publish now I have to delete the entire gh-pages
branch and re-push it just to get GitHub to update the files being served :(

I might have to put this into the release script! Thanks for mentioning
this, I'll fix tomorrow.

**Comment by ctrimble** [comment]
@joelittlejohn looks like the number one reason for this problem is not having a verified email address.  This [Stack Overflow Answer](http://stackoverflow.com/a/26837992/1818625) seems to describe the same symptoms you are seeing.

**Comment by joelittlejohn** [comment]
My email is verified so I don't think that's the problem here. There's quite a few other SO questions outlining the same problem, the only definitive fix I can find is deleting and repushing the branch. 

Links are working now. I've added a reminder to the release script to check these in future. Cheers!
