### ISSUE TITLE
Minor bug about field with same names supperated by  "_"

### ISSUE THREAD

**Issue by LOG-TAG** [joelittlejohn/jsonschema2pojo#353]
I'm getting error  'here's a problem: trying to create the same field twice: startDate'

I'm having two fields which is created by  backend dev for example 
{
"start_date":"1373964300",
 "startDate":"16/07/2013"
}

How come  startDate=start_date  !!!!    if we get ignore json format errors it will be awesome !!!

**Comment by joelittlejohn** [comment]
The problem here is that by default, propertyWordDelimiters includes the underscores, spaces and hyphens. If you want to disable this behaviour (and keep underscores as significant) then you should declare propertyWordDelimiters to not have an underscore, e.g. hyphen only:

`<propertyWordDelimiters>-</propertyWordDelimiters>`

**Comment by LOG-TAG** [comment]
Thanks for pointing out !! 

when mobile dev don't have control over a crappy back end dev guy these things happens :) Caps in json field,underscores, json starts with array rather than Object etc many more  !!

**Comment by LOG-TAG** [comment]
Thanks for pointing out !!

when mobile dev don't have control over a crappy back end dev guy these things happens :) Caps in json field,underscores, json starts with array rather than Object etc many more !!
