### ISSUE TITLE
when using object ref e.g. "$ref":"Investigation.json" and "required":"true" would it be possible to generate the @NotNull annotation

### ISSUE THREAD

**Issue by rajnotay** [joelittlejohn/jsonschema2pojo#397]

**Comment by joelittlejohn** [comment]
According to the spec, `$ref` _replaces_ the entire node, which is why `"required": true` does nothing when `$ref` is present. 

Newer versions of the JSON schema spec solved this problem however. You can use the newer form of `required` to achieve what you need (and it's supported by this plugin). It's an array that sits in the parent object and contains the names of the required properties.
