### ISSUE TITLE
When we have type Array ( List/Set ) getter should return immutable collection

### ISSUE THREAD

**Issue by maksimlikharev** [joelittlejohn/jsonschema2pojo#401]
this is how that done currently:

    @JsonProperty("prop")
    public List<MyEntity> getMyEntity() {
        return myEntity;
    }

should be:

    @JsonProperty("prop")
    public List<MyEntity> getMyEntity() {
        return Collections.unmodifiableList(myEntity);
    }

same for Set

**Comment by joelittlejohn** [comment]
This is a major breaking change, simply not possible to do this without breaking a lot of things for existing users.

We could introduce a configuration option to turn this on, but it seems rather minor to warrant this and we've already got a myriad of configuration options.

I see the value of immutability, but this is simply something that can't be changed.

**Comment by maksimlikharev** [comment]
I don't agree, maybe it is breaking change and configuration option a valuable alternative, but mutable collections are breaking thread safety, and I coast stress enough how important that is.

**Comment by joelittlejohn** [comment]
I never underestimate the importance and benefits of immutability :smile:

Java can make immutability quite costly as it requires wrappers or copies. This is one reason that many Java libraries don't offer immutability as a property of their types. To achieve thread-safety we have to go a lot further than immutable collections (generated types currently include setters), but I agree that this is one step towards that goal.

I completely agree that immutable collections should be preferred (even for mutable types, whose mutations are controlled by setters) but I feel that ship has sailed. As far as a configuration option is concerned, I'd prefer we support fully immutable types (rather than have multiple configuration options around immutability).
