### ISSUE TITLE
Missing classes ? when generating Java from a JSON document (not schema)

### ISSUE THREAD

**Issue by coderextreme** [joelittlejohn/jsonschema2pojo#439]
I concatenated all my JSON instances into a single file and ran it through:
sh jsonschema2pojo.sh -s all.json -T JSON -t X3D

I looked at the resulting class files and noticed that some stuff was missing.  Could you have a look?  One thing that was missing was Sphere.  JSON is here: https://github.com/coderextreme/x3djson/blob/master/all.json.zip?raw=true

Thanks!

**Comment by joelittlejohn** [comment]
Hi John. When jsonschema2pojo encounter an array inside an example JSON file, it uses the first array value to decide the array's type. I notice that you seem to have concatenated different JSON objects into a single array. Only the first object will be read.

We don't support arrays that contain varying types, since these would require polymorphic deserialization.

This is an assumptions about what's wrong here. If you have an example that you don't think is explained by the above, it would be useful if you could reduce this to a minimal example (rather than the full 0.5Gb json file).

**Comment by coderextreme** [comment]
It’s easy to create examples, you can just take elements out of the array.  But here’s my original source for the JSON files I concatenated together. http://www.web3d.org/x3d/content/examples/X3dExampleArchivesJsonScenes.zip <http://www.web3d.org/x3d/content/examples/X3dExampleArchivesJsonScenes.zip>  I had to filter the JSON files that wouldn’t parse. I can provide a zip with only the parseable files.   I think however, there is a issue that you bring up about polymorphic deserialization.  We might have a Geometry class which contains a IndexedFaceSet, Box, Sphere, Cone, or Cylinder, but only one of them at a time.  I see from the generated Java code that it only has IndexedFaceSet, so your explanation is good.  Do you know any JSON->JSON schema tools which support this?  Also, I’m interested in recursive JSON schemas, if you know a tool which does both.  I have Transforms within Transforms, and I only want one result Transform class.

Thanks,

John

**Comment by coderextreme** [comment]
Attached is a single example that doesn’t seem to do the right thing:
…no Shape, no Sphere, multiple Child classes (with underscores).

Thanks.  If the attachment doesn’t go through, I can put it on github with a link.

John

**Comment by joelittlejohn** [comment]
Yes, no attachment I don't think

**Comment by coderextreme** [comment]
https://raw.githubusercontent.com/coderextreme/x3djson/master/SeaStarGroup.json <https://raw.githubusercontent.com/coderextreme/x3djson/master/SeaStarGroup.json>

Thanks,

John

**Comment by coderextreme** [comment]
Multiple Child*.java classes might be acceptable.  I am not so sure about other repeated classes, and not Transforms.

I can try to find an example that generates multiple Transforms, if that will help.

John

**Comment by coderextreme** [comment]
Looks like the first example in the file has multiple transforms.  Here it is:

https://github.com/coderextreme/x3djson/blob/master/CleatClamp.json <https://github.com/coderextreme/x3djson/blob/master/CleatClamp.json>

John

**Comment by coderextreme** [comment]
Here’s an example of the worse form of nesting Transforms we have:
https://raw.githubusercontent.com/coderextreme/x3djson/master/RedPlayer.json <https://raw.githubusercontent.com/coderextreme/x3djson/master/RedPlayer.json>  probably way too many Child.java and Transform.java classes.

Even if you don’t handle polymorphism, can you notify me in the Java code or in an error log and I can deal with it?  Also, generate the subclasses of the unknown superclass without generating the inheritance hierarchy if possible.  I need the classes generated, please.  That will help immensely to have the classes.  I know what the superclass is, it comes from the XSD and the standard specification.  Unfortunately, so far, we are not generating the JSON schema from the XSD as there are differences in the JSON from the XML.  We prefix attributes, comments and arrays with @, #, - in the JSON

John

**Comment by coderextreme** [comment]
Can you suggest a good JSON Schema generator from multiple JSON files suitable for your jsonschema2pojo program?

As you can see from my issues (coderextreme) I’m not having much luck with the Schema files I try. Either no Java files are generated or one file is generated
Thanks,

John

**Comment by sandeepmeenuga** [comment]
JSONs:
=========
{
	"person" : {
            "name" : "sandeep",
	    "id" : 12,
	    "address" : {
		"add1" : "ab",
		"add2" : "cd",
		"state" : "up",
		"country" : "India"
	}
   }
}

{
	"employee" : {
              "name" : "rajesh",
	      "id" : 13,
	      "address" : {
		  "add1" : "xy",
		  "state" : "ap"
	}
    }
}

classes:
========

public class Address{
private String add1;
private String add2;
private String state;
private String country;

//setters and getters

}

public class Address_ {
private String add1;
private String state;
}


rather than creating multiple classes(with "_" symbol) is there any way to merge the existing class If we get another "address" json object in another json file.


[JSONFiles.pdf](https://github.com/joelittlejohn/jsonschema2pojo/files/43685/JSONFiles.pdf)

**Comment by joelittlejohn** [comment]
Lets discuss this on #441
