### ISSUE TITLE
Java files missing when generating from JSON Schema

### ISSUE THREAD

**Issue by coderextreme** [joelittlejohn/jsonschema2pojo#441]
Okay, I was able to generate my JSON Schema from genSON, but when I put it through jsonschema2pojo, I get nothing out

Here is the script I am running:

https://github.com/coderextreme/x3djson/blob/master/final.sh

Here are my modifications to jsonschema2pojo.sh

https://github.com/coderextreme/x3djson/blob/master/jsonschema2pojo.sh

And here is the JSON schema I am trying to generate Java from:

https://raw.githubusercontent.com/coderextreme/x3djson/master/x3dmerge.json.zip

Here's  JSON schema generated from jskemator:

https://github.com/coderextreme/x3djson/blob/master/x3d.jskemator.zip

**Comment by joelittlejohn** [comment]
It looks like all your objects here give tuple types for every array (the `items` property has an array as its value). This isn't supported by this plugin I'm afraid.

If you want to use this schema, you'll have to process it first to remove the `[` and `]` around the value of `items` all the way down.

There's a huge volume of text here - it would be useful if you could cut this down. I haven't browsed through the entire schema here so I have no idea if you require these tuple values (more than one value in the tuple, that has a different type) but if you do require it, then I'm afraid jsonschema2pojo is not the right tool for you (Java has a hard time representing tuples of mixed type). You may be interested to simply use Jackson directly or hand craft these tuple classes so that they do not use `java.util.List` to represent arrays.
