### ISSUE TITLE
Honor enum casing

### ISSUE THREAD

**Issue by dantran** [joelittlejohn/jsonschema2pojo#452]
"enum" : [ "text1", "text2" ]     get convert to enum { TEXT1, TEXT },   can we have an option to keep the original caseing?

**Comment by joelittlejohn** [comment]
We're following a fairly well established Java convention here. Is there any particular reason you need this, or is it just a cosmetic thing?

**Comment by dantran** [comment]
we have a convention at work where   dev starts out with jsonschema defintion, convert to POJO using jsonschema2pojo,  add swagger doc interface, use swagger-maven-plugin to generate swagger spec doc, finally use swagger-codegen to generate POJO at client side.

since the first schema to pojo convertion  uppercase the enum, which causes the POJO generation at swagger also use upper case, and therefor the enum contract no longer the same.

Long story why we have to use this convention.

**Comment by joelittlejohn** [comment]
Interesting, thanks for the explanation.

Do you know, is Swagger supposed to pay attention to the Jackson
annotations that appear in the Java code? I assume it must, because
sometimes property names are different from java bean property names. If
so, is it possible that this is a bug in Swagger? Should it not see that
the enum value (according to Jackson annotations) is different from the
enum name, and annotate accordingly?

I see a problem here if Swagger uses the enum name in the JSON it produces
- enum values can be very different to names, they can include characters
that are illegal in a Java name.

**Comment by dantran** [comment]
Dont think jackson has any thing to do with enum.   swagger-maven-plugin only look at java enum declaration and convert to json-schema. 

 swagger-m-p will transfer the enum's member names as is over to  jsonschema spec

Yes, we keep the enum name and value the same to prevent any confusion

**Comment by dantran** [comment]
from John

I find it strange that you start with a JSON Schema, then create POJOs from it, then generate a new JSON Schema from the POJOs. If the last step ignores Jackson annotations then there are many ways in which the output will be invalid (the schema generation must not ignore JsonProperty and JsonValue annotations).

I'm happy to accept a PR for this if you want to add a useUppercaseEnums config flag (default: true).

**Comment by joelittlejohn** [comment]
I find it strange that you start with a JSON Schema, then create POJOs from it, then generate a new JSON Schema from the POJOs. If the last step ignores Jackson annotations then there are many ways in which the output will be invalid (the schema generation must not ignore JsonProperty and JsonValue annotations).

I'm happy to accept a PR for this if you want to add a `useUppercaseEnums` config flag (default: `true`).

**Comment by dantran** [comment]
here is how jsonschema2pojo generate the enum

    @JsonProperty("state")
    private Task.State state;

    .....

    @Generated("org.jsonschema2pojo")
    public static enum State {

        QUEUED("Queued"),
        WAITING_FOR_RESOURCE("Waiting_for_resource"),
        RUNNING("Running"),
        PENDING_CANCELLATION("Pending_cancellation"),
        COMPLETED("Completed");
....

so the enum has no jackson anonotation. You may argue that swagger-m-p must parse for the enum and use the values. I found must harder to convince and harde to fix it at that side

Thank you for accepting this

**Comment by joelittlejohn** [comment]
You're missing the important bit, which is annotated in the enum with `@JsonValue`. There's no need to parse the enum, but if an enum value has a method that has the `@JsonValue` annotation then `name()` should not be used.

**Comment by dantran** [comment]
ah, i missing this

        @JsonValue
        @Override
        public String toString() {
            return this.value;
        }

I am not sure how swagger-m-p can figure out how to translate toString() to the enum's value.

Can i still submit the PR?

**Comment by joelittlejohn** [comment]
> I am not sure how swagger-m-p can figure out how to translate toString() to the enum's value.

You can submit this, but I still think you should pursue fixing this in Swagger. Obviously, I'd prefer not to have extra cruft to maintain here because of a problem or limitation in Swagger. It sounds like a genuine bug there. They need to look for the method that has `@JsonValue` and whatever value this returns should be replicated when their own model is serialized to JSON.

Imagine these examples:

`"enum": ["1", "2", "3"]`

`"enum": ["subject 1", "subject 2", "subject 3"]`

These can't be represented by an enum name. The Swagger generation must honour `@JsonValue` and at the other end (generating code for the client) it must create an enum that has a similar internal value that is different to the name. Do you agree?

**Comment by dantran** [comment]
I found a work around right at jsonschema2pojo by using 'javaEnumNames'. For my case

type: "string"
"enum" : ["text1", "text2"]
"javaEnumNames" : ["text1", "text2"]

**Comment by joelittlejohn** [comment]
Good stuff. I implemented that just a few months ago, but had completely forgotten the feature. We have too many! :D

**Comment by dantran** [comment]
Now I can pursue the fix at swagger-maven-plugin.  Thanks for helping out

**Comment by dantran** [comment]
@joelittlejohn Look like I have a long way to get the issue fixed at swagger side.  I would like to continue with this enhancement.   The work around does not look good when we have many to do.  Best to have it done in once place

**Comment by Armanda888** [comment]
Is this issue fixed in swagger-maven-plugin? or should use the workaround by adding javaEnumNames to the json file?

**Comment by joelittlejohn** [comment]
@Armanda888 I don't think so no. If you're interested in the fix I guess you would want to subscribe to kongchen/swagger-maven-plugin#258.

**Comment by dantran** [comment]
I think the fix is possible at this plugin and i dont think it is that big,  however, it is not ticked enough for me to push for PR yet
