### ISSUE TITLE
Zip of binary distribution of CLI

### ISSUE THREAD

**Issue by eliocapelati** [joelittlejohn/jsonschema2pojo#500]
In the release channel via [github](https://github.com/joelittlejohn/jsonschema2pojo/releases) please make available the binary of CLI distribution under a zip. This release enable the opportunity that the jsonschema2pojo is installed via [sdkman](http://sdkman.io/index.html).

**Comment by joelittlejohn** [comment]
Oh, thanks for reporting this. It looks like the binary upload is no longer appearing in the way it should for the last few releases.

Is sdkman able to work with a .tar.gz?

**Comment by marc0der** [comment]
We don't currently support tarballs because of discepencies between bsd and gnu tar. Sdkman expects a zip in a fairly standard SDK distribution format:

* zip contains a folder like `jsonschem2pojo-${version}`
* this in turn contains `bin` and `lib` folders for executables and jars respectively.

If you could publish such a zip on say BinTray (or wherever you like), we could easily integrate this into our platform.

Also, we can let you perform your own releases if you like, for more info, please see our [vendors page](http://sdkman.io/vendors.html).

**Comment by joelittlejohn** [comment]
Okay, so the failed uploads are just a coincidence :) GitHub has changed URL template for release uploads in a way that broke my release script, so the tars are missing from the last few versions. Thanks for helping me find that :D

I can easily add a .zip upload so that it will appear in the Download section here:

https://github.com/joelittlejohn/jsonschema2pojo/releases/tag/jsonschema2pojo-0.4.19

This would be a good time to review how the contents of the binary are structured anyway because there is stuff in there that is redundant IMO. I'll look to do this for the next release.

**Comment by marc0der** [comment]
That sounds great, we would be happy to help you distribute your cool tool!

**Comment by eliocapelati** [comment]
Thanks a lot guys!! These two tools is helping a lot of JVM developers!!!

**Comment by joelittlejohn** [comment]
The changes have been made here and there is a release that delivers the binary you need (I think):

https://github.com/joelittlejohn/jsonschema2pojo/releases/tag/jsonschema2pojo-0.4.23

Let me know if there are any more changes required.

**Comment by marc0der** [comment]
Just downloaded the binary and it's looking better. It still needs a `bin` folder containing the executables though.

**Comment by joelittlejohn** [comment]
Fixed with the latest binaries available here:

https://github.com/joelittlejohn/jsonschema2pojo/releases/tag/jsonschema2pojo-0.4.28
