### ISSUE TITLE
generateBuilders doesn't generate builders, it adds chained setters

### ISSUE THREAD

**Issue by EngineerBetter** [joelittlejohn/jsonschema2pojo#506]
I was expecting the `generateBuilders` option to generate a Builder class for each of my POJOs, but instead it adds chainable setters.

A builder would look something like this:
```
Account account = AccountBuilder.withName("foo").withEmail("test@example.com").build();
```

as opposed to

```
Account account = new Account().withName("foo").withEmail("test@example.com");
```

Perhaps the terminology could be corrected if/when the immutable classes PR gets merged?

**Comment by joelittlejohn** [comment]
Thanks for mentioning this.

I think this is a reasonably common and well understood idiom, even if not in strict agreement with the Builder pattern. The docs are clear, and I think for most people this is not a surprise for people.

The feature has existed for 4 years(?) since the earliest versions of this project. This isn't worth a rename IMO, unless (as you mention) we have a conflicting feature that does introduce builder classes.

I'm going to close this because I don't think there is enough value in renaming this property now.

**Comment by EngineerBetter** [comment]
Thanks for the response - I just figured that if I was surprised, then other people would be too. I hope it didn't come across as pedantic.

**Comment by dewthefifth** [comment]
At the risk of being a flagrant necro, I'd like to add that I wasn't surprised but I was disappointed.

My current POJO implementations all follow an immutable paradigm, where they cannot be modified after they've been constructed/built. Unfortunately, the classes generated here will not sufficiently fill the need since the builder methods will expose those otherwise immutable properties.

**Comment by sam-goodwin** [comment]
Would also like to say that I was disappointed with the generated 'builders' - I want to generate a Java POJO that only allows valid objects to be created.

**Comment by dewthefifth** [comment]
> 
> 
> Would also like to say that I was disappointed with the generated 'builders' - I want to generate a Java POJO that only allows valid objects to be created.

I'm actively working on an extension to the implemented builder that will include that feature. Specifically, when I'm done with them, hopefully not long, you'll be able to choose something like "validateOnBuild=true" and it will generate the builders with validation directly in their build method.
