### ISSUE TITLE
Add @JsonPropertyDescription when "description" property present

### ISSUE THREAD

**Issue by activey** [joelittlejohn/jsonschema2pojo#570]
As in title ;)

**Comment by joelittlejohn** [comment]
@activey If you want to see this merged into the core, we'll need to move this code into the Jackson2Annotator:

https://github.com/joelittlejohn/jsonschema2pojo/blob/c8046ceaf559840251f745eb6f00fc9839e36f9f/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java

since we support many different JSON binding libraries. The Rule classes shouldn't add Jackson annotations themselves, they should delegate to the annotator. I think in this case you'll need to add a new method to the Annotator interface (and for Jackson1, Gson, etc the implementation can do nothing).

**Comment by activey** [comment]
Ah, right, been thinking 'bout this sideeffect ;) Gonna change my code then, thanks for pointing out

**Comment by activey** [comment]
Should be better now, hopefuly ;)
