### ISSUE TITLE
Add feature to allow comments in schema files

### ISSUE THREAD

**Issue by randombk** [joelittlejohn/jsonschema2pojo#589]
Add a togglable feature to allow comments in input schema files. 

As jsonschema2pojo uses Jackson internally, this can be done by enabling the `JsonParser.Feature.ALLOW_COMMENTS` flag for the appropriate ObjectMapper instances.

**Comment by joelittlejohn** [comment]
I think we should turn this on permanently rather than introduce a configuration option, I'm happy to be relaxed about the schemas this plugin accepts in cases like this. Thanks for the info. If you'd like to submit a pull request that sets this feature on for the ObjectMappers we use then please feel free.

**Comment by randombk** [comment]
Thanks for adding this!

**Comment by yomik** [comment]
This feature is causing build issues in my android library. I upgraded jsonschema2pojo version today from 0.4.21 to 0.4.30 and it wasn't working anymore, so I downgraded until the build would pass again.
Things work until 0.4.23 and start failing with 0.4.24 : 
Looking through the changed files, this PR is probably the cause, based on the stacktrace I get : 

>  `Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jsonschema2pojo.ContentResolver
> 	at org.jsonschema2pojo.SchemaStore.<init>(SchemaStore.java:33)
> 	at org.jsonschema2pojo.rules.RuleFactory.<init>(RuleFactory.java:72)
> 	at org.jsonschema2pojo.Jsonschema2Pojo.createRuleFactory(Jsonschema2Pojo.java:96)
> 	at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:56)
> 	at org.jsonschema2pojo.Jsonschema2Pojo$generate.call(Unknown Source)
> 	at org.jsonschema2pojo.gradle.GenerateJsonSchemaAndroidTask.generate(GenerateJsonSchemaAndroidTask.groovy:53)
> 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)`

Which is caused by the following error : 

> `Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;
> 	at org.jsonschema2pojo.ContentResolver.<clinit>(ContentResolver.java:42)
> 	at org.jsonschema2pojo.SchemaStore.<init>(SchemaStore.java:33)
> 	at org.jsonschema2pojo.rules.RuleFactory.<init>(RuleFactory.java:72)
> 	at org.jsonschema2pojo.Jsonschema2Pojo.createRuleFactory(Jsonschema2Pojo.java:96)
> 	at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:56)
> 	at org.jsonschema2pojo.Jsonschema2Pojo$generate.call(Unknown Source)
> 	at org.jsonschema2pojo.gradle.GenerateJsonSchemaAndroidTask.generate(GenerateJsonSchemaAndroidTask.groovy:53)
> 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
> `

Note that I'm using gson in this specific project.

**Comment by joelittlejohn** [comment]
@yomik Are you using the Gradle or Maven plugin? It looks like you have a conflict in the Jackson version that is on the plugin classpath. We require Jackson 2.5.0 or later.
