### ISSUE TITLE
jsonschema2pojo creates java classes with underscores in case of same schema node in different schema file.

### ISSUE THREAD

**Issue by githubusr87** [joelittlejohn/jsonschema2pojo#628]
Hi, I am new to jsonschema2pojo.

I am using this plugin in my project to generate pojo classes. We have many json schema files and some schema nodes in the file are repetitive in more than 1 file with different attributes but same node name. 

First time when it finds the node, java class created properly with "nodename".java but when it parses the same node in different file again  it creates the java class with "_"(underscore), And creates classes by appending more underscores for the next occurrences of same node.

Ex:
Action.java
Action_.java
Action__.java
Action___.java
Action_____.java

Problem i am having is, If schema is updated with same node or new schema is added in future, then the pojo classes gets generated differently with underscores, And i have to fix these compile errors in my source code.

I cant change the schema files as it is provided by 3rd party , I want the java class name to be created with json file name prefixing on it. How can i prefix filename to java class name ? Or is there any better solution to my problem. 

Kindly help. Thank you.

**Comment by joelittlejohn** [comment]
I think what you need here is the patch that was submitted in #622. I'm not sure this patch can go into the core yet, but if you wanted to build your own version from [this branch](https://github.com/libgraviton/jsonschema2pojo/tree/feature/keep-field-context) then you could solve your problem.

Another option is to add javaType to your Action objects so that they each get a permanent name that you decide. Much better to give your objects a canonical name that is unambiguous IMO.
