### ISSUE TITLE
Support @XmlRootElement annotation

### ISSUE THREAD

**Issue by koh-osug** [joelittlejohn/jsonschema2pojo#662]
When using REST based frameworks which are using JAXB mapping conventions the XmlRootElement annotation is required.

**Comment by joelittlejohn** [comment]
Creating types for XML binding isn't a goal of this project, but you can to write your own custom annotator to do this. I'd recommend sharing that if you can.

The best way to do this is to extend this class:

https://github.com/joelittlejohn/jsonschema2pojo/blob/9f5ca13b3ffa04893b501229343891e042965d1b/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AbstractAnnotator.java

You can use the existing some of the existing annotator implementations for examples.

**Comment by koh-osug** [comment]
What is the best way in Maven to include this single class file in the Maven classpath during build time? I cannot have a separate project just containing a single class. It should just reside in the same folder like the project using this. What would be the correct Maven folder for compiling and adding this file to the Maven classpath  automatically before the build starts? Or is it necessary to write a hack to get this file compiled and included?

**Comment by joelittlejohn** [comment]
You can't add this class into the same module that you're generating sources for because, by definition, compilation happens after generating sources (and the annotator needs to be compiled before it can help with generating source files). There isn't a Maven folder inside a single module that can help you here.

The solution here is a separate project or at least a separate module. If you build this as a separate module you can also publish this to other projects and users.

**Comment by koh-osug** [comment]
Ok, thanks. I will add this annotation line by some filter expression after the source was generated, this seems to be faster for the class I have here.
