### ISSUE TITLE
how to define or add classpath?

### ISSUE THREAD

**Issue by kkuo** [joelittlejohn/jsonschema2pojo#667]
I have a class that we are using, com.company.Ipv4AndPort and I defined a schema to use it:

```
{
    "title" : "foo",
    "type": "object",
    "properties": {
        "$ref": "com.company.Ipv4AndPort"
    }
}
```

problem is, in the generated sources directory I see a new POJO, "Ipv4AndPort", and under the package "com.company". So this causes the two classes to conflict. What do I need to do to add the classpath so that jsonschema2pojo will use the existing class and not generate a new one?

**Comment by joelittlejohn** [comment]
We need a Gradle user to answer this :)

**Comment by ben-manes** [comment]
Library dependencies are supported, but project ones aren't. That would require some ClassLoader workaround, if I recall correctly. I did that when contributing the Flyway plugin so we could look at that as an example. But it's messier because we have to load all, as we don't know a filter to restrict with.

But I don't understand why the code generator requires that. It's outputting text, so it should rely on javac and be dumb. That would be my preference and how I avoid this problem when using JavaPoet.

**Comment by joelittlejohn** [comment]
@ben-manes When you say 'Library dependencies are supported' do you mean this should just work if the library is a project dependency or do you mean it's supported if you add a reference to the library somewhere special in the Gradle script?

**Comment by ben-manes** [comment]
There is an example with the plugin of a jodatime dependency. It requires using the classpath scope in buildscript. But that classloader is for Gradle process.

**Comment by joelittlejohn** [comment]
@kkuo If this class is within _the same project_ then I don't think it is a goal of ours to use it. You can reference existing classes from libraries, but not classes from the same project in which you are currently generating sources.

@ben-manes I understand where you're coming from re relying on javac to decide whether the class is present and correct, however the behaviour of this project is that you can reference existing classes, and the classpath (and the existence of a class) is the only way we have to know whether a class exists.

**Comment by ben-manes** [comment]
@joelittlejohn Is that a limitation of the code generator's metamodel or does it support the more naive form of outputting raw code blocks?

**Comment by ben-manes** [comment]
The code I used for Flyway looks pretty benign, so it's possible. But you have to run compileJava before the codegen task, so there can't be interdependencies within the module.

 https://github.com/ben-manes/gradle-flyway-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/flyway/task/AbstractFlywayTask.groovy#L208

**Comment by joelittlejohn** [comment]
I think this would be a helpful addition. Would this (or something similar) allow multi-module Gradle projects to have one module that generates classes which are dependent on another module in the same project?

**Comment by ben-manes** [comment]
It should. To do that we'd also use `sourceSets.main.compileClasspath` which would bring in all dependency jars (other modules and external dependencies).

However that is for the Java plugin. Android likes to break the Java ecosystem and can be very frustrating to work with. So there is a reasonable chance we would have to debug a slight variation.

**Comment by seprich** [comment]
Hi, do I understand correctly from the previous discussion that it is a design decision to not support binding of classes from the same project source sets? From the usage point of view this becomes a bit frustrating when handling enum:s in MVC application, because normally I would want to define enums at the model layer but then I cannot make js2p generated classes to make use of those existing enums. js2p insists on making its own versions of the enums and then in controller code I am left to make either dubious `E1.values()[value.ordinal()]` conversions (not safe for production code) or explicit static converter functions just to convert between almost identical enum implementations. Removing enum definitions from model layer and using js2p generated enums through the application is possible but not necessarily a good idea. 1) can be confusing if enum used for DB is defined in json schema. 2) Same enum will be referenced in multiple places inside the schema. Which one will be the master definition?

**Comment by ben-manes** [comment]
My understanding is that it is a restriction of the code generator and a limitation of the plugin.

The code generator requires that it can resolve every class referenced. This means that you can't have circular dependencies within a single module, since either javacc or the codegen would fail. Many other generators handle this by generating code with raw strings and deferring the correctness check to the java compiler.

The Gradle plugin does not support classes from module dependencies to be used by the code generator. The discussion described how that could be implemented.

It sounds like if the plugin was enhanced that might resolve your issue.

**Comment by joelittlejohn** [comment]
One problem we have here is that when the `javaType` rule is used the only way we have of knowing whether this refers to an existing type is that this type can be found on the classpath. If it is found on the classpath we use it, if it is not found then we generate a new class using javaType as the FQCN.

I think allowing code to be used from sibling modules would be a huge step forward here and I was surprised to learn that this doesn't work for Gradle users. With this addition, at least people can reuse classes within the same project, albeit in a different module.

**Comment by joelittlejohn** [comment]
This is resolved since 1.x. If you want to use an existing class, you must now use `existingJavaType` (and there is no requirement for the class to existing in order for jsonschema2pojo to skip generation).
