### ISSUE TITLE
Parsing multi array json

### ISSUE THREAD

**Issue by arya6000** [joelittlejohn/jsonschema2pojo#676]
There is a bug with the jsonschema2pojo that I posted about on Stackoverflow. It's a fairly long post, so I think it will be better if I post the stackoverflow link instead as I have everything formatted there. 

Can you please tell me  what workarounds I can do? here is the link to the stackoverflow question

http://stackoverflow.com/questions/41533067/parsing-multi-array-json-into-pojo

**Comment by joelittlejohn** [comment]
It looks like you have a valid answer on StackOverflow. This library does not support arrays that have a varying type (we take the List type from the first element).

**Comment by turchinc** [comment]
@joelittlejohn  coming back to this issue and my similar recent inquery on SO:

https://stackoverflow.com/questions/73226110/jsonschema2pojo-type-creation-for-list-of-objects?noredirect=1#comment129326510_73226110

it seems a list of object and even a list of a simple enum of string is not really supported:

```
"channel": {
"type": "array",
"items": [{
	"type": "string",
	"enum": ["Print", "Webshop"]
}],
	"uniqueItems": true
},
```
The generated interface `public Set<Object> getChannel()` does not help the developer to use only the values for the enum. It does not even tell them it is a list of String :( 
And whil enum allowing single values are well supported and code for them gets generated, the enum here (only used in array since multiple values are permitted) is not even generated into code (since there is no occurence where it is used as a single value (which works fine!). 

Is that also to be expected?

**Comment by joelittlejohn** [comment]
Was it intentional that you put the items schema into an array?

**Comment by turchinc** [comment]
I'm only a user of the schema. But the reason for the array is that more
than one value is allowed for the enum e.g

Print
Or
Web
Or
[Print, Web]


If there is a better way to model this I'm happy to pass a suggestion along
to the schema authors.

**Comment by joelittlejohn** [comment]
So if I understand correctly, these are all valid:

```json
"channels": ["Print"]
```
```json
"channels": ["Webshop"]
```
```json
"channels": ["Print", "Webshop"]
```

I believe you want this:

```json
"items": {
  "type": "string",
  "enum": ["Print", "Webshop"]
}
```

and not this:

```json
"items": [{
  "type": "string",
  "enum": ["Print", "Webshop"]
}]
```

so the `"items"` schema is not inside an array.

Currently, the schema implies that the channels items should have a fixed length of one. I don't believe this is what you want.

I do think we could improve jsonschema2pojo here by supporting arrays for `"items"` whenever the array of schemas has only one schema within it.

**Comment by turchinc** [comment]
@joelittlejohn  thanks for this guidance. I will pass it along to the maintainer of the schema.
