### ISSUE TITLE
Add initializeCollections configuration option to jsonschema2pojo.org UI

### ISSUE THREAD

**Issue by yccheok** [joelittlejohn/jsonschema2pojo#691]
Joshua Bloch seems to recommend empty collection class instead of null.

https://books.google.com.my/books?id=ka2VUBqHiWkC&pg=PA201&lpg=PA201&dq=josh+bloch+empty+list+instead+of+null&source=bl&ots=yZKmOfq-V4&sig=D3Nv2o2Ixp3uF769r0nBxqS3Vek&hl=en&sa=X&redir_esc=y#v=onepage&q=josh%20bloch%20empty%20list%20instead%20of%20null&f=false

Can we have an option, instead of initializing collections class as null

    public class CreateSessionResponse {
        @SerializedName("accounts")
        @Expose
        private List<Account> accounts = null;

Can we have

    public class CreateSessionResponse {
        @SerializedName("accounts")
        @Expose
        private List<Account> accounts = Collections.emptyList();

**Comment by joelittlejohn** [comment]
`Collections.emptyList()` can be problematic for some people because it returns an immutable list. This is often not what people expect when they come to use the list later.

We already have an option to initialize collections:

https://joelittlejohn.github.io/jsonschema2pojo/site/0.4.30/generate-mojo.html#initializeCollections

You can choose to either have them initialized to empty collections, or set to null. This option is present in version 0.4.4 and later.

Do you mean you want this option exposed at jsonschema2pojo.org?

**Comment by yccheok** [comment]
Ya. I am referring to that web site. Thank u for your information!
