### ISSUE TITLE
Question - Invalid JSON causing List to be set to null - forcing a null check on a collection

### ISSUE THREAD

**Issue by broot02** [joelittlejohn/jsonschema2pojo#692]
We are reading an entity from a JSON response, and noticed that when an array (based on JSON schema) is set to null, the List is also being set as null. 

Invalid JSON
`{ "testArray": null }`

As compared to valid JSON
`{ "testArray" : [] }`

Initially, I thought the issue was that the initializeCollection was not defaulting to true as expected, but that is not the case. 

My thought process is as follows we are defaulting initializeCollection to true, to avoid needing to check if a list is null, we should just check to see if it is empty. With that said if are just setting the List to null, it kind of defeats the purpose of initializeCollections. Thoughts?

I guess this is more of a question at this point, I cannot force these changes to go back on the webservice this JSON is coming from, so I am left dealing with the aftermath, I can simply add a null check, was hoping there was something I am missing in the configuraton.

**Comment by joelittlejohn** [comment]
Hi @broot02. I think I have understood your problem but please do correct me if not.

This question is related to the data binding library you are using rather than jsonschema2pojo IMO. We generate types that will initialize collection fields according to your preference (via the `initializeCollections` config option). When it comes to data binding though, if you explicitly have a null in your JSON data then this will be set onto your instance. The value `null` is different to a missing value and I think your data binding library is acting correctly when it sets the collection field to a null value on your instance.

`initializeCollections: true` dictates that a collection should be _initialized_ and empty when an instance is created, it doesn't mean stop the field ever being set to null later.

Are you using Jackson?

It's interesting that that Jackson ObjectMapper can be configured to do the opposite of what you want (use the value `null` instead of an empty list when the JSON includes an empty JSON array) with [this option](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/DeserializationFeature.java#L352). However I don't see a way to configure the Object Mapper to avoid binding a null value (or treat null as empty list).

I think you'll have to solve this by registering a custom type deserializer. Extend one of the existing deserializers but add the 'translate `null` to empty List' behavoiur you want.

**Comment by broot02** [comment]
Ok, thanks. I was hoping I was missing some "magic" configuration that maybe would have added an annotation, at this point I will just add a null check(due to time constraints), even though it is quite saddening lol

Thanks again
