### ISSUE TITLE
Add custom annotator to the maven plugin's classpath

### ISSUE THREAD

**Issue by abhardwaj4** [joelittlejohn/jsonschema2pojo#722]
I have a custom annotator (`CustomAnnotator extends AbstractAnnotator`) which adds a custom annotation to the generated POJOs using `<customAnnotator>` option. 

If I have the annotator and the annotation in a separate lib, I can include that lib as this plugin's dependency. But if I have the annotator and the annotation in the same project where I am generating POJOs, is there any way to have them on the plugin's classpath ?

**Comment by abhardwaj4** [comment]
I ended up creating multi-module project, added custom annotator and annotation in one module and referred this module in the second module which generates the source code from the schemas. Closing this issue. Please label it as a question.

**Comment by joelittlejohn** [comment]
@abhardwaj4 Yes, this is the best approach. Since Maven has only one compile phase it's not possible to have the compiled custom annotator class available _before_ you generate sources that have to be compiled within the same module.

**Comment by Damonio** [comment]
I don't think is the best approach for all the scenarios to have a separate maven module to compile Custom Annotation, in my case I only have one custom annotation in the project that I want to use, and I don't see the sense to create a separate module only to build this annotation. Regarding maven that only do one compilation, you can easily specify maven to build twice before maven runs the plugin jsonschema2pojo like this:

` <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
                <executions>
                    <execution>
                        <id>default-compile</id>
                    </execution>
                    <execution>
                        <id>generate-annotations</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <source>${java.version}</source>
                            <target>${java.version}</target>
                            <includes>
                                <include>**/precompiled/*</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>`

 Now, the problem is that even doing this it seems that jsonschema2pojo still wants you to reference this as a dependency

**Comment by Damonio** [comment]
I was able to find out exactly why you can't do that, the main reason is that the Json2Pojo is a maven build plugin, and because of that, it has a separate classloader:

https://maven.apache.org/guides/mini/guide-maven-classloading.html

3. Plugin Classloaders
After that, each plugin has its own classloader that is a child of Maven's core classloader. The classes in this classloader are taken from the dependencies in the plugin's dependency list.

Users can add dependencies to this classloader by adding dependencies to a plugin in the plugins/plugin section of their project pom.xml. Here is a sample of adding ant-nodeps to the plugin classloader of the Antrun Plugin and hereby enabling the use of additional/optional Ant tasks:
```
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-antrun-plugin</artifactId>
              <version>1.3</version>
              <dependencies>
                <dependency>
                  <groupId>org.apache.ant</groupId>
                  <artifactId>ant-nodeps</artifactId>
                  <version>1.7.1</version>
                </dependency>
              </dependencies>
              ...
            </plugin>
```
Plugins can inspect their effective runtime class path via the expressions ${plugin.artifacts} or ${plugin.artifactMap} to have a list or map, respectively, of resolved artifacts injected from the PluginDescriptor.

Please note that the plugin classloader does neither contain the dependencies of the current project nor its build output. Instead, plugins can query the project's compile, runtime and test class path from the MavenProject in combination with the mojo annotation requiresDependencyResolution from the Mojo API Specification. For instance, flagging a mojo with @requiresDependencyResolution runtime enables it to query the runtime class path of the current project from which it could create further classloaders.

When a build plugin is executed, the thread's context classloader is set to the plugin classloader.
