### ISSUE TITLE
Unit Testing custom annotator values

### ISSUE THREAD

**Issue by abhardwaj4** [joelittlejohn/jsonschema2pojo#727]
I am writing a unit test for a custom annotator. The annotator annotates the generated class with `@JsonFilter` annotation and adds a parameter value for the filter. It also annotates certain class fields with a custom annotation.

I am able to test for the presence of `@JsonFilter` annotation on the generated model but I am not able access the value `"MyJacksonSerializeFilter"` in String form using any public API of `JAnnotationUse` class. 
The generated class looks like as shown below. Is there any API that I can use to test this value ?

```
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonFilter("MyJacksonSerializeFilter")
public class Account
{
  @JsonProperty("accountNumber")
  @JsonPropertyDescription("Account number")
  private String accountNumber;
  @JsonProperty("status")
  @JsonPropertyDescription("The current status of the account.")
  private String status;
```

**Comment by joelittlejohn** [comment]
This sounds like a question for the CodeModel project. Unfortunately, not every part of the CodeModel state is accessible so I don't think you can assert anything about this in your unit test. 

One option would be to output the code and look for the expected string. Another option would be to write some other kind of test where you actually use your generated class and see if it behaves as expected (does it actually use the correct Jackson filter), since this is the real requirement that you should be checking for.
