### ISSUE TITLE
multiple references create _ . require override option and referencing the same across several objects

### ISSUE THREAD

**Issue by sripathitk** [joelittlejohn/jsonschema2pojo#749]
I have two elements which refer a common element  in a single Json schema. when Java objects are created , multiple references are created with _ as appended . ideally i would want to override the class and use the same one in all classes. Is there any way this can be handled.
  
{
  "manageCallListReferences": {
    "type": "object",
    "additionalDetails": {
      "type": "object",
      "properties": {
        
      }
    }
  }
}
																	 
	 and i have another element with 																	 
																
{																	 
"splitLiabilityData": {
  "type": "object",
  "properties": {
    "additionalDetails": {
      "type": "object",
      xxxxxx
    }
  }
}
}

it would create additionalDetails_.java multiple times.

**Comment by joelittlejohn** [comment]
Can you see how bizarrely your description has been formatted? This makes it very hard to read. Please see the GitHub docs on how to format code blocks:

https://guides.github.com/features/mastering-markdown/

In your case, simply put this before the code:

    ```json

and this after the code:

    ````

Now regarding this issue. If you want to re-use the same schema here (so that this plugin knows you are referring to the same object) then you should use a json schema `$ref`. Please not though, if you use `$ref` it is advisable to use `javaType` inside the `additionalDetails` schema so that the naming of this class is always consistent.
