### ISSUE TITLE
Registering invalid inputs and outputs via TaskInputs and TaskOutputs

### ISSUE THREAD

**Issue by kuc** [joelittlejohn/jsonschema2pojo#809]
```
A problem was found with the configuration of task ':xyz:generateJsonSchema2Pojo'.
Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been
deprecated and is scheduled to be removed in Gradle 5.0.
 - Cannot write to file 'C:\xyz\zyx\jsonschema2pojo' specified for property '$2' as it is a directory.
```
Caused by #748 

Untested solution - change:
```
outputs.files project.files(configuration.targetDirectory)
```
to
```
outputs.dir configuration.targetDirectory
```

**Comment by brinzi** [comment]
Any solution to this?

**Comment by joelittlejohn** [comment]
@brinzi If you or @kuc can provide a PR to fix this, I'm happy to merge it for the next release.

**Comment by lared** [comment]
I have the very same issue preventing us from migrating to Gradle 5.0. It occurs when I build a project for the second time. It's caused by the output validation described above, also as seen in 4.3 release notes (paragraph about input/output validation) - validation is failing when the output directory/file exists, apparently.

I'll try to create the smallest reproducible example and maybe a PR when I have some more time (maybe over the weekend).

It's possible that removing this line: https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy#L49

while preserving this one: https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy#L45

would be sufficient to remedy the issue.

**Comment by lared** [comment]
I've reproduced it here on 4.10.2:

https://github.com/lared/js2p-gradle-plugin-output-validation/tree/master

And here with 5.0-rc-4:

https://github.com/lared/js2p-gradle-plugin-output-validation/tree/gradle_5

I'm having some issues with surefire JVMs dying when building `jsonschema2pojo`, so I'm likely not going to try making a fix today.

**Comment by lared** [comment]
I've checked, and the removal seems to work just fine with all three versions:

https://github.com/lared/js2p-gradle-plugin-output-validation/tree/gradle_2_after_fix
https://github.com/lared/js2p-gradle-plugin-output-validation/tree/gradle_4_after_fix
https://github.com/lared/js2p-gradle-plugin-output-validation/tree/gradle_5_after_fix

Will provide a PR shortly. Sorry for spamming a bit.

**Comment by joelittlejohn** [comment]
> Will provide a PR shortly. Sorry for spamming a bit.

Not at all, these updates are great! Thank you for taking the time to look at this and share your progress.
