### ISSUE TITLE
Easy way to add Methods to Java classes

### ISSUE THREAD

**Issue by joelittlejohn** [joelittlejohn/jsonschema2pojo#81]
_Original author: JasonBog...@gmail.com (November 28, 2012 14:46:24)_

Using auto-generated code is great, but it's hard to add other methods to the generated classes when they will be overwritten on the next Maven build.

Here's what I suggest:
- Make all the generated classes abstract, so that they must be subclassed to be instantiated.
- Prefix all the generated class names with the underbar ( _ ).
- Generate another set of classes the same name as the first set, but without the underbar.
- Have the second set of classes extend their corresponding abstract class. 
- Set the body of these classes blank with a &quot;TODO&quot; statement telling the user to add &quot;additional class methods here&quot;.
- Generate the abstract underbar classes -every time- with the just the POJO getter and setter methods like it does now.
- Generate the non-underbar classes only -if they don't exist- on the file system with no class methods.

Examples attached

_Original issue: http://code.google.com/p/jsonschema2pojo/issues/detail?id=81_

**Comment by githubjul** [comment]
Hi @joelittlejohn 

I know that this issue is closed, but I wanted to add 2 thigns : first of all, thank you for jsonschema2pojo I think it is very useful !!
Then, I've just discovered this issue and wanted to add that I am using your generator with the same kind of behavior than the one described by Jason.
I am doing some post processing to make the class abstract, add custom methods, ....

So I just wanted to add that he was not alone to want this kind of functionalities.

I'm still learning how to use your code and customize the generation, so maybe I miss some features.

Thanks again !
