### ISSUE TITLE
Options to create only referenced entities from *.json schema file.

### ISSUE THREAD

**Issue by lvimalchandran** [joelittlejohn/jsonschema2pojo#813]
use case: I have two json schema file A.json and B.json. 
Here A.json is the parent structure and it refers all its complex types to B.json.
but B.json has lots of unreferenced(orphan) complex types declared for future use. Now if I use both A.json and B.json in jsonschema2pojo to create pojo classes. It creates all the declared entities (referenced/unreferenced) in the target folder.

I am looking for any options to set in order to exclude all the unreferenced/orphan entities while creating pojo classes. Please let me know if there is an option already available.

Thanks.

**Comment by joelittlejohn** [comment]
If you point the plugin at A.json (instead of the directory) it will only generate the types required/referenced for A.

Alternatively, if you have more than two schemas, you could separate A and B into separate directories. In the first directory put the schemas you want generated types for, and from these schemas you can reference things in the second directory. Point the plugin at the first directory when you want to generate types.

**Comment by lvimalchandran** [comment]
Thanks Joe. I have tried the first option and it works per my expectation. Thanks for your quick response.
