### ISSUE TITLE
Classes may get many underscores

### ISSUE THREAD

**Issue by sdettmer** [joelittlejohn/jsonschema2pojo#868]
Hi,

I have a JSON schema where a sub type (in my case, "Payload") is used many times in different objects. The classes generated differ by number of underscores, so I have for example "Payload___________________________________.java" and "Payload__________________________________.java" (and all shorter names and many longer ones). Of course these classes are hard to distinguish in IDE e.g. Netbeans. Could the naming be changed to have something like e.g. "Payload_35.java" instead?

**Comment by joelittlejohn** [comment]
Hi

If you are re-using the same type repeatedly, you should investigate using `$ref` which will re-use the same class.

If these are different types and you want to keep these as separate classes, you'll find that 1.0.0-alpha2 actually already has the behaviour you need, because @SergioModulusData contributed #476. Instead of adding a `_` every time, you'll get output named like:

Payload__1.java, Payload__2.java, Payload__3.java...

**Comment by sdettmer** [comment]
Ahh, that are great news, thank you!
(We cannot use $ref, because the types differ, and no, I cannot change it :))
