### ISSUE TITLE
No failure when a javaType class already exists

### ISSUE THREAD

**Issue by jota3** [joelittlejohn/jsonschema2pojo#887]
Hi,

I just realised that two schemes of my project were referencing the same **javaType** class (with different properties) though no exception was raised during the generation of the classes. Is that expected ? If yes, how can I prevent a referenced **javaType** class to be generated if it's already been generated from another scheme.

Thanks.

**Comment by joelittlejohn** [comment]
What version of jsonschema2pojo are you using?

**Comment by jota3** [comment]
It's the 0.4.0 version.

**Comment by joelittlejohn** [comment]
If you use 1.0.0-alpha4, you will find that **javaType** has now been split into **javaType** and **existingJavaType**. If you want to influence the name of a new type, you use javaType, if you want to refer to an existing type from the classpath, you use existingJavaType. This should solve problems like the one you are having, because you explicitly choose which scenario is correct.

So if you use 1.0.0-alpha4, using javaType to refer to a class that has already been generated should be an error. I have not tried this but I believe it is how 1.0.0-alpha4 will function.

**Comment by jota3** [comment]
Does the last non-alpha version already include **existingJavaType** ?

**Comment by joelittlejohn** [comment]
Closing this as it's solved in the current alpha release and will be available in 1.0.0.
