### ISSUE TITLE
1.0.0-beta1: Enum is not getting the classNamePrefix

### ISSUE THREAD

**Issue by LarsKrogJensen** [joelittlejohn/jsonschema2pojo#938]
If I configure my maven plugin with classNamePrefix all generated classes gets this prefix, but enum doesn't. Is this by design or a bug?

**Comment by joelittlejohn** [comment]
Yes, this is the expected behaviour. Since enums are typically static inner classes, adding prefixes and suffixes to them seems redundant. There is a feature request open already for enumNameSuffix which I think should also include enumNamePrefix: https://github.com/joelittlejohn/jsonschema2pojo/issues/852.

**Comment by LarsKrogJensen** [comment]
OK, a good feature would be as suggested in #852, enumPrefix/Suffix.
Enums are very often shared, and then it makes sense to not have it as inner class.
