### ISSUE TITLE
Add support for multiple naming conventions for generated properties

### ISSUE THREAD

**Issue by acsbendi** [joelittlejohn/jsonschema2pojo#968]
It would be a useful feature to add an option to enable naming conventions different from the conventional Java naming convention for the generated properties.
For example:
From this: 
```json
{
  "full_name": "abc",
  "phone_number": "+1-541-754-3010",
  "has_subscription": false
}
```

it could generate this:

```java
public class User {

    private String full_name;
    private String phone_number;
    private Boolean has_subscription;

    public String getfull_name() {
        return full_name;
    }

    public void setfull_name(String full_name) {
        this.full_name = full_name;
    }

    public String getphone_number() {
        return phone_number;
    }

    public void setphone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    public Boolean gethas_subscription() {
        return has_subscription;
    }

    public void sethas_subscription(Boolean has_subscription) {
        this.has_subscription = has_subscription;
    }
}
```

Use case: I would like to generate a Kotlin class from it (with Android studio), while also keeping the original naming conventions used in the json object.

**Comment by joelittlejohn** [comment]
If you just want to leave the underscores in place, then you can do this by removing the `_` from the list of property word delimiters. The default list is ` -_` (space, hyphen and underscore).

If you want us to generate method names without the capitalized first field letter, then I'm afraid we will never support this, because these would not be value getter/setter methods.

**Comment by acsbendi** [comment]
@joelittlejohn Thank you, removing the `_` solves the problem :)
