### ISSUE TITLE
Document / clarify which JSON Schema version/draft is supported

### ISSUE THREAD

**Issue by JoshLitt** [joelittlejohn/jsonschema2pojo#979]
I assume this supports draft-04, since that is the most commonly supported version. I see unit tests referring to draft-04, but I also see 2 unit tests referring to draft-07. Since 04 and 07 are not entirely compatible, it leaves me wondering what is actually supported.

**Comment by joelittlejohn** [comment]
Hi. We don't have a specific draft number that is supported. This tool was created when JSON Schema was in its infancy, but we have tried to support as much of the JSON Schema syntax across all drafts as is practical (including some changes that were made in draft04 and also some formats that were added in later drafts).

The major additions in draft04, oneOf/allOf/anyOf are not supported by this tool, mainly due to the difficulty in using the Java type system to accurately and adequately represent the semantics of those JSON Schema rules.

You mention that drafts 04 and 07 are not entirely compatible. Which parts are you referring to exactly?
