### ISSUE TITLE
[URGENT] [help wanted] is there a way to map List to our custom implementation

### ISSUE THREAD

**Issue by kartikpatodi** [joelittlejohn/jsonschema2pojo#995]

**Comment by satya8453** [comment]
Wanted to replace the generated pojo fields datatypes with our custom classes instead of Java classes. Is there any way to do so ? For e.g. instead of using **private String name** for a generated POJO, we want it to be generated as **private Text name**, where in Text is our custom class. hope to find a reply soon.

**Comment by joelittlejohn** [comment]
Yes, you can use existingJavaType for this:

https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#existingjavatype

**Comment by kartikpatodi** [comment]
@joelittlejohn Is there a way to configure it in the maven plugin or as a setter in the api?
As we have a use case with only a json file.

**Comment by joelittlejohn** [comment]
No, not possible I'm afraid. You can fork the library and modify though.
